application:
  name: generate-example-project    # 应用名
  debug: true        # 调试模式
  server:
    http:
      port: 8080
      read_timeout: 30s    # 添加超时配置
      write_timeout: 30s
    grpc:
      port: 8082
      max_concurrent_streams: 100
  monitor:
    prometheus:
      enable: false      # Enable prometheus client
      path: "metrics"   # Default value is "metrics", set path as needed.
      scrape_interval: "15s"  # 添加采集间隔
    pprof:
      enable: false  # Enable PProf tool
      port: 8080
      enabled_endpoints: ["goroutine", "heap"]  # 指定启用的端点
kafka:
  enable: false
  topic: ["XXX"]
  group_id: "XXX"
  bootstrap_servers: "XXX:XX,XXX:XX,XXX:XX"
  security_protocol: "PLAINTEXT"
  sasl_mechanism: "PLAIN"
  sasl_username: "XXX"
  sasl_password: "XXX"
database:
  enable: false
  db_type: "mysql"
#  dsn: "user:passwd@tcp(*******:8306)/lg_server?charset=utf8mb4&parseTime=True&loc=Local&timeout=20s"
#  dsn: "user=postgres password=halojeff host=127.0.0.1 port=8432 dbname=lg_server sslmode=disable TimeZone=Asia/Shanghai"
  host: "*******"
  port: 8306
  username: root
  password: "*******"
  database: dbname
  args:
    - name: charset
      value: utf8mb4
  log_mode: "info"
  max_idle_conn: 10
  max_open_conn: 100
es:
  enable: false
  endpoints:
    - "*******:8776"
  username: elastic
  password: "*************"
  api_key: # 认证方式2（可选）
  is_https: true
  ca_cert: # CA证书
  insecure_skip_verify: false   # 跳过证书认证，生产应为false
redis:
  enable: false
  endpoints:
    - "*******:8379"
  password: "*******"
  index_db: 0
  MinIdleConns: 10
  max_idle_conns: 50
  max_active_conns: 10
  max_retry_times: 5
  master_name:
  sentinel_username:
  sentinel_password:
rabbitmq:
  enable: false
  host: "*******"
  port: 8672
  username: lucas
  password: "*******"
crypto:
  - type: aes
    key: "wrEDGh75pxAUH8Mr"
  - type: des
    key: "b_K3prT8"
